// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'age': string;
  'blocklist': string;
  'customFormatScore': string;
  'download': string;
  'downloadIcon': string;
  'history': string;
  'indexer': string;
  'indexerFlags': string;
  'interactiveIcon': string;
  'languages': string;
  'manualDownloadContent': string;
  'negativeScore': string;
  'peers': string;
  'positiveScore': string;
  'protocol': string;
  'quality': string;
  'rejected': string;
  'row': string;
  'sceneMapping': string;
  'size': string;
  'titleContent': string;
}
export const cssExports: CssExports;
export default cssExports;
